apiVersion: v1
kind: Pod
metadata: 
    name: frontend
spec:
    containers: 
        - name: frontend
          image: gnagamani/frontend 
---
apiVersion: v1
kind: Pod
metadata: 
    name: cart
spec:
    containers: 
        - name: cart
          image: gnagamani/cart 
---
apiVersion: v1
kind: Pod
metadata: 
    name: catalogue
spec:
    containers: 
        - name: catalogue
          image: gnagamani/catalogue
---
apiVersion: v1
kind: Pod
metadata: 
    name: user
spec:
    containers: 
        - name: user
          image: gnagamani/user 
---
apiVersion: v1
kind: Pod
metadata: 
    name: payment
spec:
    containers: 
        - name: payment
          image: gnagamani/payment 
---
apiVersion: v1
kind: Pod
metadata: 
    name: shipping
spec:
    containers: 
        - name: shipping
          image: gnagamani/shipping 
          